### ISSUE TITLE
How to scroll? and rebind keys

### ISSUE THREAD

**Issue by nebunebu** [juienpro/kebihelp#1]
I'm just testing this out. How do you scroll down? When viewing a tab? How do you remap keypresses for toggling tabs? Left and right arrows works for moving to the previous and next tab, but I would prefer being able to use h and l, and j and k for scrolling up and down.

**Comment by juienpro** [comment]
Patch in progress

**Comment by juienpro** [comment]
It should be better. 

- You can set up the fixed size of the Window, and scroll if the content does not fit.
- You can remap keys

See the Readme.

The v0.1.2 has been published on Pypi. 

To upgrade in your venv: `pip install kebihelp --upgrade`
